version: '3.8'

services:
  jenkins-blueocean:
    image: myjenkins-blueocean:2.414.2
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this points to the correct Dockerfile location
    restart: on-failure
    networks:
      - jenkins
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"

  docker-socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    restart: always
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:2376:2375"

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
